//
//  Constants.swift
//  Muslim Guide
//
//  Created by macboock pro on 6/11/20.
//  Copyright © 2020 macboock pro. All rights reserved.
//

import Foundation

struct Constants {
    static let baseURL="https://api.aladhan.com/v1/calendar?"
    static let defultLatitude=51.508515
    static let defultLongitude = -0.1254872
    static let defultCityName = "London"
    static let prayers = ["Fajr","Dhuhr","Asr","Maghrib","Isha"]
    static let defultMethod = "Muslim World League"
    static let appRefresh="com.MuslimGuide.appRefresh"
    static let dataBaseCleaning="com.MuslimGuide.dataBaseCleaning"
    static let userPermissionEnabled = "notificationsPermission"
    static let separateLines = "separateLines"
    static let methods:[String:Int]=[
        "Shia Ithna-Ansari":0,
        "University of Islamic Sciences":1,
        "Karachi":1,
        "Islamic Society of North America":2,
        "Muslim World League":3,
        "Umm al-Qura, Makkah":4,
        "Egyptian General Authority of Survey":5,
        "Institute of Geophysics":7,
        "University of Tehran":7,
        "Gulf Region":8,
        "Kuwait":9,
        "Qatar":10,
        "Majlis Ugama Islam Singapura":11,
        "Singapore":11,
        "Islamic Organisations Union of France":12,
        "Diyanet İşleri Başkanlığı, Turkey":13,
        "Spiritual Administration of Muslims of Russia":14
    ]
    
    static let defultMethodCountries:[String:String]=[
          "Afghanistan":"University of Islamic Sciences",
          "Albania":"Muslim World League",
          "Algeria":"Egyptian General Authority of Survey",
          "Angola":"Muslim World League",
          "Anguilla":"Muslim World League",
          "Antigua and Barbuda":"Muslim World League",
          "Argentina":"Muslim World League",
          "Armenia":"Muslim World League",
          "Aruba":"Muslim World League",
          "Australia":"Muslim World League",
          "Austria":"Muslim World League",
          "Azerbaijan":"Muslim World League",
          "Bahamas":"Muslim World League",
          "Bahrain":"Umm al-Qura, Makkah",
          "Bangladesh":"University of Islamic Sciences",
          "Barbados":"Muslim World League",
          "Belarus":"Muslim World League",
          "Belgium":"Muslim World League",
          "Belize":"Muslim World League",
          "Benin":"Muslim World League",
          "Bhutan":"Muslim World League",
          "Bolivia":"Muslim World League",
          "Bosnia-Herzegovina":"Muslim World League",
          "Botswana":"Muslim World League",
          "Brazil":"Muslim World League",
          "British Virgin Islands":"Muslim World League",
          "Bulgaria":"Muslim World League",
          "Burkina Faso":"Muslim World League",
          "Burundi":"Muslim World League",
          "Cambodia":"Muslim World League",
          "Cameroon":"Muslim World League",
          "Canada":"Islamic Society of North America",
          "Cayman Islands":"Muslim World League",
          "Central African Republic":"Muslim World League",
          "Chad":"Muslim World League",
          "Chile":"Muslim World League",
          "China":"Muslim World League",
          "Colombia":"Muslim World League",
          "Congo":"Muslim World League",
          "Costa Rica":"Muslim World League",
          "Croatia":" Muslim World League",
          "Cuba":" Muslim World League",
          "Cyprus":"Muslim World League",
          "Czech Republic":"Muslim World League",
          "Democratic Republic Congo":"Muslim World League",
          "Denmark":"Muslim World League",
          "Djibouti":"Muslim World League",
          "Dominica":"Muslim World League",
          "Dominican Republic":"Muslim World League",
          "Ecuador":"Muslim World League",
          "Egypt":"Egyptian General Authority of Survey",
          "El Salvador":"Muslim World League",
          "Equatorial Guinea":"Muslim World League",
          "Eritrea":"Muslim World League",
          "Estonia":"Muslim World League",
          "Ethiopia":"Muslim World League",
          "Falkland Islands":"Muslim World League",
          "Fiji":"Muslim World League",
          "Finland":"Muslim World League",
          "France":"Islamic Organisations Union of France",
          "French Guiana":"Muslim World League",
          "Gabon":"Muslim World League",
          "Gambia":"Muslim World League",
          "Georgia":"Muslim World League",
          "Germany":"Muslim World League",
          "Ghana":"Muslim World League",
          "Gibraltar":"Muslim World League",
          "Greece":"Muslim World League",
          "Grenada":"Muslim World League",
          "Guatemala":"Muslim World League",
          "Guinea":"Muslim World League",
          "Guinea Bissau":"Muslim World League",
          "Guyana":"Muslim World League",
          "Haiti":"Muslim World League",
          "Honduras":"Muslim World League",
          "Hong Kong":"Muslim World League",
          "Hungary":"Muslim World League",
          "India":"University of Islamic Sciences",
          "Indonesia":"Muslim World League",
          "Iran":"Muslim World League",
          "Iraq":"Muslim World League",
          "Ireland":"Muslim World League",
          "Isle Of Man":"Muslim World League",
          "Italy":"Muslim World League",
          "Jamaica":"Muslim World League",
          "Japan":"Muslim World League",
          "Jordan":"Umm al-Qura, Makkah",
          "Kazakhstan":"Muslim World League",
          "Kenya":"Muslim World League",
          "Kosovo":"Muslim World League",
          "Kuwait":"Umm al-Qura, Makkah",
          "Kyrgyzstan":"Muslim World League",
          "Latvia":"Muslim World League",
          "Lebanon":"Muslim World League",
          "Liberia":"Muslim World League",
          "Libya":"Egyptian General Authority of Survey",
          "Lithuania":"Muslim World League",
          "Luxembourg":"Muslim World League",
          "Madagascar":"Muslim World League",
          "Malawi":"Muslim World League",
          "Malaysia":"Muslim World League",
          "Maldives":"Muslim World League",
          "Malta":"Muslim World League",
          "Martinique":"Muslim World League",
          "Mauritania":"Muslim World League",
          "Mexico":"Muslim World League",
          "Moldova":"Muslim World League",
          "Monaco":"Muslim World League",
          "Montserrat":"Muslim World League",
          "Morocco":"Muslim World League",
          "Mozambique":"Muslim World League",
          "Myanmar":"Muslim World League",
          "Namibia":"Muslim World League",
          "Nepal":"Muslim World League",
          "Netherlands":"Muslim World League",
          "New Zealand":"Muslim World League",
          "Nicaragua":"Muslim World League",
          "Niger":"Muslim World League",
          "Nigeria":"Egyptian General Authority of Survey",
          "Korea":"Muslim World League",
          "Norway":"Muslim World League",
          "Oman":"Umm al-Qura, Makkah",
          "Pakistan":"University of Islamic Sciences",
          "Palestine":"Muslim World League",
          "Panama":"Muslim World League",
          "Papua New Guinea":"Muslim World League",
          "Paraguay":"Muslim World League",
          "Peru":"Muslim World League",
          "Philippines":"Muslim World League",
          "Poland":"Muslim World League",
          "Portugal":"Muslim World League",
          "Puerto Rico":"Muslim World League",
          "Qatar":"Umm al-Qura, Makkah",
          "Romania":"Muslim World League",
          "Russia":"Muslim World League",
          "Rwanda":"Muslim World League",
          "Saint Lucia":"Muslim World League",
          "Saint Vincent and the Grenadines":"Muslim World League",
          "Saudi Arabia":"Umm al-Qura, Makkah",
          "Senegal":"Muslim World League",
          "Seychelles":"Muslim World League",
          "Sierra Leone":"Muslim World League",
          "Singapore":"Majlis Ugama Islam Singapura",
          "Slovakia":"Muslim World League",
          "Slovenia":"Muslim World League",
          "Solomon Islands":"Muslim World League",
          "Somalia":"Muslim World League",
          "South Africa":"Muslim World League",
          "South Korea":"Muslim World League",
          "South Sudan":"Egyptian General Authority of Survey",
          "Spain":"Muslim World League",
          "Sri Lanka":"Muslim World League",
          "Sudan":"Egyptian General Authority of Survey",
          "Suriname":"Muslim World League",
          "Swaziland":"Muslim World League",
          "Sweden":"Muslim World League",
          "Switzerland":"Muslim World League",
          "Syria":"Umm al-Qura, Makkah",
          "Taiwan":"Muslim World League",
          "Tajikistan":"Muslim World League",
          "Tanzania":"Muslim World League",
          "Thailand":"Muslim World League",
          "Togo":"Muslim World League",
          "Trinidad And Tobago":"Muslim World League",
          "Tunisia":"Muslim World League",
          "Turkey":"Muslim World League",
          "Turkmenistan":"Muslim World League",
          "Turks Caicos Islands":"Muslim World League",
          "Uganda":"Muslim World League",
          "UK":"Islamic Society of North America",
          "Ukraine":"Muslim World League",
          "United Arab Emirates":"Umm al-Qura, Makkah",
          "United States Virgin Islands":"Muslim World League",
          "Uruguay":"Muslim World League",
          "USA":"Islamic Society of North America",
          "Uzbekistan":"Muslim World League",
          "Venezuela":"Muslim World League",
          "Vietnam":"Muslim World League",
          "Yemen":"Umm al-Qura, Makkah",
          "Zambia":"Muslim World League",
          "Zimbabwe":"Muslim World League"]
    
}
